function tracks_folder(num_keys)
%% Author: Akhil Nagariya RRC, IIIT Hyderabad
% The function is used to genrerate tracks across "num_keys" number of frames
% It reads the keyfiles (foldet seq_0/left_rijvi_keys and seq_0/right_rijvi_keys),
% mentioned in the keylist file (folder seq_0/rijvi_list_keys) and uses corresponding   
% Track file (folder seq_0/rijvi_tracks) 
% generated by rajvi shah's code and uses them to create a feature file 
% under the folder rijvi_tracks_feature which contains X and Y poition of
% the corresponding features for these frames. File format:
% feature1: X1 Y1 X2 Y2 X3 Y3 .... Xnum_keys Ynum_keys
% feature2: X1 Y1 .... Xnum_keys Ynum_keys
%  .
%  .
%  .

%specify sequence
seq = 'seq_0';

%list all the files inside the keypoint directory

list = dir(strcat('/home/akhil/visual_odom/',seq,'/rijvi_list_keys/'));
num_keys = 5;
for i = 1:size(list)-3
    if i == 18 
        continue;
    end
    keyfile = cell(num_keys,1);
    %compute tracks index from index track file
    tracks = compute_tracks(strcat('/home/akhil/visual_odom/',seq,'/rijvi_tracks/',int2str(i+2),'.txt'))
    %open feature file to write tracks
    feature_tracks=strcat('/home/akhil/visual_odom/',seq,'/rijvi_tracks_features/',int2str(i+2),'.txt')
    f2= fopen(feature_tracks,'w')
    %open keyfile to read the keys 
    fid = fopen(strcat('/home/akhil/visual_odom/',seq,'/rijvi_list_keys/',int2str(i),'.txt'));
    for j=1:num_keys
%         fid = fopen(strcat('/home/akhil/visual_odom/',seq,'/rijvi_list_keys/',list(i+2).name));
        tline = fgets(fid);
        %save all the keyfile in keyfile variable
        keyfile{j} = tline;
    end
    fclose(fid);
    %for each track find the X,Y postion in each frame (keyfile)
    for j=2:size(tracks,1)
        for k=1:num_keys-1
            keyfile{k,1}
            %open keyfile k and get the X,Y location of the index mentioned
            %in tracks index variable namely "track"
            f= fopen(strcat(keyfile{k,1}));
            g = textscan(f,'%s','delimiter','\n');
            points=sscanf(g{1}{2+8*tracks(j,k)},'%f');
            %write the correspoding point the feature file
            fprintf(f2,'%f %f ',points(1),points(2));
            fclose(f);
        end
        % same procedure as in the for loop for the last keyfile ('\n')
        k = k+1;
        keyfile{k,1}
        f= fopen(strcat(keyfile{k,1}));
        g = textscan(f,'%s','delimiter','\n');
        points=sscanf(g{1}{2+8*tracks(j,k)},'%f');
        fprintf(f2,'%f %f\n',points(1),points(2));
        fclose(f);
    end
end